### log ###
logging:
  level:
    root: info
#    root: debug

### connect ###
todoist:
  baseUrl: https://api.todoist.com/rest/v2
  token: ${TOKEN_TODOIST}
dictionary: #будет заменено на бд
  path: /app/resources/dict/dictionary.yml
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:postgresql://34.65.32.51:5432/buylistdb
    username: postdb
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

### deploy ###
management:
  endpoint:
    health:
      probes:
        enabled: true
